services:
  - type: web
    name: expense-tracker
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://expense-tracker-db:5432/expensetrackerdb
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: expense-tracker-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: expense-tracker-db
          property: password

databases:
  - name: expense-tracker-db
    databaseName: expensetrackerdb
    user: postgres
    plan: free
    region: singapore
