spring.application.name=expense-tracker
server.port=${PORT:8080}

# Disable H2 console in postgres profile
spring.h2.console.enabled=false

# PostgreSQL Database Configuration (Passed dynamically by Render / Cloud)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.tracker.expensetracker=INFO
